version: '3.9'
services:

  authentication-db:
    image: postgres:13
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5



  authentication-service:
    build: ./services/auth
    depends_on:
      - authentication-db
    environment:
      DATABASE_URL: "postgresql://authuser:authpass@authentication-db:5432/authdb"

    ports:
      - "4001:4000"