version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - ./microservices/database/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./microservices/database/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: node:18-alpine
    working_dir: /app
    volumes:
      # Mount your code into /app
      - ./microservices/auth:/app
      # Use a named volume for node_modules to preserve them after npm install
      - app_node_modules:/app/node_modules
    command: sh -c "npm install && npm run build && npm start"
    environment:
      DATABASE_URL: "postgresql://authuser:authpass@postgres:5432/authdb"
    depends_on:
      - postgres
    ports:
      - "4001:4000"

volumes:
  app_node_modules: