services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      # Run your SQL file on first startup
      - ./Backend/src/database/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-service:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./Backend:/app
      - app_node_modules:/app/node_modules
    command: sh -c "npm install && npm run build && npm start"
    environment:
      DATABASE_URL: "postgresql://authuser:authpass@postgres:5432/authdb"
      CRYPT_SECRET: "hello"
    depends_on:
      - postgres
    ports:
      - "4001:4000"

volumes:
  app_node_modules:
  postgres_data: